--U - user defined table
USE MiniFacebook
GO

IF OBJECT_ID('Likes', 'U') IS NOT NULL
	DROP TABLE Likes
IF OBJECT_ID('Comments', 'U') IS NOT NULL
	DROP TABLE Comments
IF OBJECT_ID('Pages', 'U') IS NOT NULL
	DROP TABLE Pages
IF OBJECT_ID('Posts', 'U') IS NOT NULL
	DROP TABLE Posts
IF OBJECT_ID('Categories', 'U') IS NOT NULL
	DROP TABLE Categories
IF OBJECT_ID('Users', 'U') IS NOT NULL
	DROP TABLE Users

CREATE TABLE Users (
	ID INT PRIMARY KEY IDENTITY(1, 1),
	UserName VARCHAR(100),
	City VARCHAR(50),
	DOB DATE
)

CREATE TABLE Categories (
	ID INT PRIMARY KEY IDENTITY(1, 1),
	CName VARCHAR(100),
	CDescription VARCHAR(50)
)

CREATE TABLE Posts (
	ID INT PRIMARY KEY IDENTITY(1, 1),
	PDate DATE,
	PText VARCHAR(200),
	Shares INT,
	UserID INT REFERENCES Users(ID)
)

CREATE TABLE Pages (
	ID INT PRIMARY KEY IDENTITY(1, 1),
	PName VARCHAR(100),
	CID INT REFERENCES Categories(ID)
)

CREATE TABLE Comments (
	ID INT PRIMARY KEY IDENTITY(1, 1),
	CDate DATE,
	CText VARCHAR(200),
	Shares INT,
	TopComm BIT,
	PID INT REFERENCES Posts(ID)
)

CREATE TABLE Likes (
	UserID INT REFERENCES Users(ID),
	PageID INT REFERENCES Pages(ID),
	LDate DATE,
	PRIMARY KEY(UserID, PageID)
)

GO

INSERT Users(UserName, City, DOB) VALUES('John', 'Cluj', '1-4-2019');
INSERT Users(UserName, City, DOB) VALUES('Johnny', 'Bucharest', '2-5-2019');
INSERT Posts(PDate, PText, Shares, UserID) VALUES('12-3-2019', 'Some Text', 20, 1);

SET TRANSACTION ISOLATION LEVEL REPEATABLE READ
BEGIN TRAN
SELECT * FROM Users WHERE ID = 1
WAITFOR DELAY '00:00:05'
SELECT * FROM Users WHERE ID = 1
COMMIT TRAN